export enum TypeGarantie {
  CAUTION_PROVISOIRE = 'CAUTION_PROVISOIRE',
  CAUTION_DEFINITIVE = 'CAUTION_DEFINITIVE',
  RETENUE_DE_GARANTIE = 'RETENUE_DE_GARANTIE',
  CAUTION_AVANCE = 'CAUTION_AVANCE'
}
